# Generated by Django 5.0.6 on 2024-06-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(),
        ),
    ]
